import { Brain, Sparkles, Zap } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'

const CARDS = [
  {
    icon: Sparkles,
    title: 'Executive Narrative',
    desc: 'Natural-language summary of current risk posture, key drivers, and recommended focus areas, generated by an LLM from structured signals.',
  },
  {
    icon: Zap,
    title: 'Anomaly Explanations',
    desc: 'When statistical anomalies are detected, the LLM will provide context-aware explanations referencing historical patterns and seasonal norms.',
  },
  {
    icon: Brain,
    title: 'Recommendation Narratives',
    desc: 'Each rule-based recommendation will be augmented with LLM-generated rationale, drawing on incident history and best practice.',
  },
  {
    icon: Sparkles,
    title: 'Cross-Site Intelligence',
    desc: 'Pattern recognition across all sites to surface systemic risks that individual-site analysis may miss.',
  },
]

export function AIInsights() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-xl bg-primary/15 flex items-center justify-center">
          <Brain className="h-5 w-5 text-primary" />
        </div>
        <div>
          <h2 className="text-lg font-bold text-foreground">AI Insights</h2>
          <p className="text-sm text-muted-foreground">LLM-powered risk narrative — coming in Phase 9</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {CARDS.map(({ icon: Icon, title, desc }, i) => (
          <Card key={i} className="card-hover animate-fade-rise">
            <CardContent className="py-5 flex gap-3">
              <div className="h-9 w-9 rounded-lg flex items-center justify-center shrink-0 bg-primary/10">
                <Icon className="h-[18px] w-[18px] text-primary" />
              </div>
              <div>
                <p className="text-sm font-semibold text-foreground">{title}</p>
                <p className="text-sm text-muted-foreground mt-1">{desc}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
