"""
Insights API — rule-based narrative insights for the AI Insights tab.

GET /api/insights/{site}?quarter=YYYY-Qn
    Returns the three deterministic narrative sections + the underlying
    signal block, generated by app.services.ai_insights.generate_site_insight.

No external LLM is called.  Results are cached for 5 minutes per (site, quarter)
inside the service so re-renders don't re-compute.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.services.ai_insights import generate_site_insight

router = APIRouter(prefix="/api/insights", tags=["insights"])


@router.get("/{site}")
def get_site_insight(
    site: str,
    quarter: str = Query(..., description="Fiscal-quarter label, e.g. '2025-Q4'"),
    db: Session = Depends(get_db),
):
    return generate_site_insight(site, quarter, db)
